import { Product } from "./types";

// Replace with a real DB/CMS fetch later (e.g. getProducts() from Prisma, Sanity, Shopify, etc).
// Image URLs are placeholders — swap with your actual product photography.
export const products: Product[] = [
  {
    id: "1",
    slug: "black-oversized-tee",
    name: "black oversized tee",
    category: "t-shirts",
    price: 1,
    originalPrice: 1124,
    rating: 4.6,
    reviewCount: 2340,
    imageUrl: "https://picsum.photos/seed/black-tee/600/800",
    isBestseller: true,
    colors: ["#1C1B19", "#F3EFE7"],
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    id: "2",
    slug: "olive-oversized-tee",
    name: "olive oversized tee",
    category: "t-shirts",
    price: 899,
    rating: 4.4,
    reviewCount: 980,
    imageUrl: "https://picsum.photos/seed/olive-tee/600/800",
    colors: ["#6B5B45"],
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: "3",
    slug: "printed-graphic-tee",
    name: "printed graphic tee",
    category: "t-shirts",
    price: 949,
    rating: 4.5,
    reviewCount: 610,
    imageUrl: "https://picsum.photos/seed/graphic-tee/600/800",
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: "4",
    slug: "fleece-hoodie",
    name: "fleece hoodie",
    category: "hoodies",
    price: 1799,
    rating: 4.7,
    reviewCount: 1520,
    imageUrl: "https://picsum.photos/seed/fleece-hoodie/600/800",
    isBestseller: true,
    sizes: ["M", "L", "XL", "XXL"],
  },
  {
    id: "5",
    slug: "zip-up-hoodie",
    name: "zip-up hoodie",
    category: "hoodies",
    price: 1999,
    rating: 4.3,
    reviewCount: 410,
    imageUrl: "https://picsum.photos/seed/zip-hoodie/600/800",
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: "6",
    slug: "pullover-hoodie",
    name: "pullover hoodie",
    category: "hoodies",
    price: 1699,
    rating: 4.5,
    reviewCount: 305,
    imageUrl: "https://picsum.photos/seed/pullover-hoodie/600/800",
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    id: "7",
    slug: "co-ord-pyjama-set",
    name: "co-ord pyjama set",
    category: "pyjamas",
    price: 1499,
    rating: 4.6,
    reviewCount: 275,
    imageUrl: "https://picsum.photos/seed/pyjama-set/600/800",
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: "8",
    slug: "striped-pyjama-set",
    name: "striped pyjama set",
    category: "pyjamas",
    price: 1399,
    rating: 4.2,
    reviewCount: 140,
    imageUrl: "https://picsum.photos/seed/striped-pyjama/600/800",
    sizes: ["M", "L", "XL"],
  },
];

export const getBestsellers = () => products.filter((p) => p.isBestseller);
export const getNewArrivals = () => products.slice(0, 4);
export const getFeatured = () => products.slice(2, 6);
export const getTrending = () => products.slice(4, 8);